name: superchat
description: "Complete, customizable, and highly scalable chat package"
version: 0.0.2
homepage: https://github.com/thruthesky/superchat

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: 4.19.5
  firebase_auth_platform_interface: 7.2.6
  firebase_auth_web: 5.11.5
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_database: 10.5.5
  firebase_database_web: "0.2.5+5"
  firebase_ui_database: 1.4.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
