// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsPVi-9-1OzNDpPUk1QXBSUnSlYhbuw94',
    appId: '1:955598266475:web:f9424de05df837cb8f512e',
    messagingSenderId: '955598266475',
    projectId: 'withcenter-test-6',
    authDomain: 'withcenter-test-6.firebaseapp.com',
    databaseURL: 'https://withcenter-test-6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-test-6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeL3T21iN8OgQtUfL_9DSxp2eCjovXM_4',
    appId: '1:955598266475:android:204e19dc6885439f8f512e',
    messagingSenderId: '955598266475',
    projectId: 'withcenter-test-6',
    databaseURL: 'https://withcenter-test-6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-test-6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDDzOJV5CsbEqKPKcunJdWR9kN94yy2_s',
    appId: '1:955598266475:ios:adec8f33b00539a28f512e',
    messagingSenderId: '955598266475',
    projectId: 'withcenter-test-6',
    databaseURL: 'https://withcenter-test-6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-test-6.appspot.com',
    iosBundleId: 'com.superchat.example',
  );
}
